print("Welcome to Dungeon Crawler")
print("Who dares to enter the dungeon?")
name = input()
print("Foolish " + name + ", you will soon meet your end!")
print("Tell me, are you a hunter, thief, magician, or warrior?")
class1 = input()
print("If you are a " + class1 + " like you say you are, how many attack points do you have out of 100?")
attack = input()
print("Alright, how many points did you leave yourself for magic?")
magic = input()
print("Well " + name + " you may enter the dungeon. Hopefully a " + class1 + " like yourself can survive with only " + attack + " attack points, and " + magic + " magic points.")
print("Good luck!")
